---
title: Kris Ma
email: 
description: ''
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
permalink: "/:categories/:title/"
paginate: "5"
paginate_path: "/page:num/"
timezone: 
include:
- _pages
plugins:
- jekyll-menus
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  name: Kris Ma
  avatar: "/assets/images/bio-photo.jpg"
  bio: Foodie at Microsoft AI and Research. Loves machine learning, financial engineering,
    and cooking.
  links:
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/krisma
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/kris_maaaa
footer:
  links:
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/
defaults:
- scope:
    path: 
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: 
    type: pages
  values:
    layout: single
    author_profile: true
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
